### ISSUE TITLE
How setup swagger for a express server , which does not have models ???

### ISSUE THREAD

**Issue by skalyanapu-mtuity** [shawngong/Swagger-Node-Express-For-Existing-APIs#11]
Hello,

I'm working on a use case, where an express server will not have models i.e DB models, just APi which renders provided JSON files. I tried all the steps getting an error as below:+1: 

`err TypeError: Cannot read property 'get' of null
    at Swagger.configure (/home/sai/Projects/mServiceMaster/mServiceMaster-service/node_modules/swagger-node-express/Common/node/swagger.js:84:18)
    at config.init.then.then.then.serviceInfo (/home/sai/Projects/mServiceMaster/mServiceMaster-service/mServiceMaster-service.js:75:13)
    at tryCatcher (/home/sai/Projects/mServiceMaster/mServiceMaster-service/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/sai/Projects/mServiceMaster/mServiceMaster-service/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/sai/Projects/mServiceMaster/mServiceMaster-service/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/sai/Projects/mServiceMaster/mServiceMaster-service/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/sai/Projects/mServiceMaster/mServiceMaster-service/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/sai/Projects/mServiceMaster/mServiceMaster-service/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/sai/Projects/mServiceMaster/mServiceMaster-service/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/sai/Projects/mServiceMaster/mServiceMaster-service/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
`
any suggestion how to setup swagger for express server app , which do not db models ..

**Comment by michal93cz** [comment]
I have also this problem, @skalyanapu-mtuity did you find any solution for this?
